import type { NodeType, RelationType } from '@mkg/shared';

/** Per node_type fill color (设计文档 §6.4 + 三个层级类型 + v2 操作流程/风险/错误/措施/评分项). */
export const NODE_COLORS: Record<NodeType, string> = {
  textbook: '#1E40AF',
  chapter: '#2563EB',
  section: '#3B82F6',
  knowledge_point: '#3B82F6',
  term: '#10B981',
  operation_process: '#0EA5E9',
  operation_step: '#F59E0B',
  competency: '#8B5CF6',
  risk: '#EF4444',
  error: '#F97316',
  measure: '#10B981',
  assessment_item: '#A855F7',
  image: '#EC4899',
  table: '#06B6D4',
  question: '#EF4444',
  case: '#92400E',
};

export const NODE_TYPE_LABELS: Record<NodeType, string> = {
  textbook: '教材',
  chapter: '章',
  section: '节',
  knowledge_point: '知识点',
  term: '术语',
  operation_process: '操作流程',
  operation_step: '操作步骤',
  competency: '能力',
  risk: '风险',
  error: '常见错误',
  measure: '处理措施',
  assessment_item: '评分项',
  image: '图像',
  table: '表格',
  question: '题目',
  case: '病例',
};

export const RELATION_TYPE_LABELS: Record<RelationType, string> = {
  CONTAINS: '包含',
  BELONGS_TO: '属于',
  HAS_CHAPTER: '含章',
  HAS_SECTION: '含节',
  HAS_KNOWLEDGE_POINT: '含知识点',
  HAS_PROCESS: '含流程',
  HAS_STEP: '含步骤',
  NEXT_STEP: '下一步',
  PREREQUISITE_OF: '前置',
  EASILY_CONFUSED_WITH: '易混',
  RELATED_TO: '相关',
  ILLUSTRATED_BY: '图示',
  DESCRIBED_IN: '描述于',
  TESTED_BY: '考核',
  APPLIED_IN: '应用于',
  STANDARD_TERM_OF: '标准术语',
  SYNONYM_OF: '同义',
  HAS_TERM: '含术语',
  ALIAS_OF: '别名',
  SUPPORTS_COMPETENCY: '支撑能力',
  ASSESSED_BY: '评分项',
  HAS_RISK: '风险',
  HANDLED_BY: '处理',
  PREVENTED_BY: '预防',
  MANIFESTED_AS: '表现为',
  COMMON_ERROR_OF: '常见错误',
  BELONGS_TO_GRAPH: '属于图谱',
  MERGED_INTO: '合并到',
  RELATED_GRAPH: '相关图谱',
};

export const CANDIDATE_BORDER = '2px dashed #9CA3AF';
export const APPROVED_BORDER = '2px solid #111827';
